#服务器端口
server:
  port: 8200

#数据源配置
#spring:
#  datasource:
#    url: ${kc.datasource.prod.url}
#    username: ${kc.datasource.prod.username}
#    password: ${kc.datasource.prod.password}

spring:
  #排除DruidDataSourceAutoConfigure
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
#        master:
#          url: ${kc.datasource.mysql.url}
#          username: ${kc.datasource.mysql.username}
#          password: ${kc.datasource.mysql.password}
#        slave:
#          url: ${kc.datasource.highgo.url}
#          username: ${kc.datasource.highgo.username}
#          password: ${kc.datasource.highgo.password}
#
        master:
          url: jdbc:mysql://192.168.202.55:8099/tb_psdc?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: qiscisp
          password: QISSC@22tianbo
        slave:
            url: jdbc:postgresql://192.168.202.18:5866/exchange?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
            username: highgo
            password: highgo@123
