#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/tianbo/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tianbo.**.entity
  configuration:
    cache-enabled: true

#swagger扫描路径配置
swagger:
  base-packages:
    - com.tianbo


#oss配置
oss:
  enable: true
  name: minio
  tenant-mode: false
  endpoint: http://127.0.0.1:9000
  access-key: D99KGE6ZTQXSATTJWU24
  secret-key: QyVqGnhIQQE734UYSUFlGOZViE6+ZlDEfUG3NjhJ
  bucket-name: kc
spring:
  profiles:
    active: dev
#cxf配置
cxf:
  path: /cxf